name: Build Windows Vulkan

on:
  workflow_dispatch:
  push:
    branches:
      - upstream-fix

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v6

      - name: Install Vulkan SDK
        shell: pwsh
        run: |
          curl.exe -L --output "$env:TEMP\VulkanSDK-Installer.exe" "https://sdk.lunarg.com/sdk/download/1.3.296.0/windows/VulkanSDK-1.3.296.0-Installer.exe"
          Start-Process -Wait -FilePath "$env:TEMP\VulkanSDK-Installer.exe" -ArgumentList "--root", "C:\VulkanSDK", "--accept-licenses", "--default-answer", "--confirm-command", "install"

      - name: Configure CMake
        shell: cmd
        run: set VULKAN_SDK=C:\VulkanSDK && set PATH=C:\VulkanSDK\Bin;%PATH% && cmake -B build -DLLAMA_VULKAN=ON -DLLAMA_CURL=OFF -DCMAKE_DISABLE_FIND_PACKAGE_OpenSSL=ON -DCMAKE_BUILD_TYPE=Release

      - name: Build
        shell: cmd
        run: cmake --build build --config Release -j4

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: llama-win-vulkan
          path: build/bin/Release/
          if-no-files-found: error
